Rpg_Hero_Creator/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from Rpg_Hero_Creator import settings
from warhammer.views import HeroCreationView, HeroView, UserLoginView, AddUserView, UserProfileView, UserLogoutView, \
    HeroesSearchAndView, \
    MainSiteView, HeroDeleteView, AssignExperienceView, AddNewsView, DeleteNewsView, EditNewsView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', MainSiteView.as_view(), name="index"),
    url(r'^warhammer/hero-creation/', HeroCreationView.as_view(), name='warhammer-hero-creation'),
    url(r'^warhammer/hero/(?P<hero_id>(\d+))$', HeroView.as_view(), name="warhammer-hero-view"),
    url(r'^warhammer/heroes/', HeroesSearchAndView.as_view(), name='warhammer-heroes'),
    url(r'^warhammer/hero/delete/(?P<hero_id>(\d+))$', HeroDeleteView.as_view(), name='warhammer-hero-delete'),
    url(r'^warhammer/assign-experience/', AssignExperienceView.as_view(), name='warhammer-assign-experience'),

    url(r'^warhammer/add-news/', AddNewsView.as_view(), name='warhammer-add-news'),
    url(r'^warhammer/delete-news/(?P<news_id>(\d+))$', DeleteNewsView.as_view(), name='warhammer-news-delete'),
    url(r'^warhammer/edit-news/(?P<news_id>(\d+))$', EditNewsView.as_view(), name='warhammer-news-edit'),

    url(r'^user-profile/(?P<user_id>(\d+))$', UserProfileView.as_view(), name='user-profile'),
    url(r'^user-login/', UserLoginView.as_view(), name='user-login'),
    url(r'^user-logout/', UserLogoutView.as_view(), name='user-logout'),
    url(r'^add-user/', AddUserView.as_view(), name='add-user'),
]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

warhammer/models.py
from datetime import datetime

from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator
from django.contrib.auth.models import User
import os

RACES = (
    ("human", "Human"),
    ("dwarf", "Dwarf"),
    ("elf", "Elf"),
    ("halfling", "Halfling"),
)

GENDERS = (
    ("male", "Male"),
    ("female", "Female"),
)

CAREERS = (
    ("agitator", "Agitator"), ("apprentice_wizard", "Apprentice Wizard"), ("bailiff", "Bailiff"),
    ("barber-surgeon", "Barber-Surgeon"), ("boatman", "Boatman"), ("bodyguard", "Bodyguard"),
    ("bone_picker", "Bone Picker"), ("bounty_hunter", "Bounty Hunter"), ("burgher", "Burgher"),
    ("camp_follower", "Camp Follower"), ("charcoal-burner", "Charcoal-Burner"), ("coachman", "Coachman"),
    ("entertainer", "Entertainer"), ("envoy", "Envoy"), ("estalian_diestro", "Estalian Diestro"),
    ("ferryman", "Ferryman"), ("fieldwarden", "Fieldwarden"), ("fisherman", "Fisherman"),
    ("grave_robber", "Grave Robber"), ("hedge_wizard", "Hedge Wizard"), ("hunter", "Hunter"),
    ("initiate", "Initiate"), ("jailer", "Jailer"), ("kislevite_kossar", "Kislevite Kossar"),
    ("kithband_warrior", "Kithband Warrior"), ("marine", "Marine"), ("mercenary", "Mercenary"),
    ("messenger", "Messenger"), ("militiaman", "Militiaman"), ("miner", "Miner"), ("noble", "Noble"),
    ("norse_berserker", "Norse Berserker"), ("outlaw", "Outlaw"), ("outrider", "Outrider"),
    ("peasant", "Peasant"), ("pit_fighter", "Pit Fighter"), ("protagonist", "Protagonist"),
    ("rat_catcher", "Rat Catcher"), ("roadwarden", "Roadwarden"), ("rogue", "Rogue"),
    ("runebearer", "Runebearer"), ("scribe", "Scribe"), ("seaman", "Seaman"), ("servant", "Servant"),
    ("shieldbreaker", "Shieldbreaker"), ("smuggler", "Smuggler"), ("soldier", "Soldier"),
    ("squire", "Squire"), ("student", "Student"), ("thief", "Thief"), ("thug", "Thug"),
    ("toll_keeper", "Toll Keeper"), ("tomb_robber", "Tomb Robber"), ("tradesman", "Tradesman"),
    ("troll_slayer", "Troll Slayer"), ("vagabond", "Vagabond"), ("valet", "Valet"),
    ("watchman", "Watchman"), ("woodsman", "Woodsman"), ("zealot", "Zealot")
)


def get_image_path(instance, filename):
    return os.path.join('../media/portraits', str(instance.id), filename)


class Hero(models.Model):
    def __str__(self):
        return self.name
    name = models.CharField(max_length=32, blank=True, null=True)
    race = models.CharField(max_length=16, choices=RACES, default="Human")
    current_career = models.CharField(max_length=32, choices=CAREERS, default="Mercenary")
    previous_careers = models.CharField(max_length=32, null=True, blank=True)
    age = models.SmallIntegerField(null=True, blank=True)
    gender = models.CharField(choices=GENDERS, max_length=16, default="Male")
    # unimportant
    eye_color = models.CharField(max_length=16, null=True, blank=True)
    hair_color = models.CharField(max_length=16, null=True, blank=True)
    weight = models.SmallIntegerField(null=True, blank=True)
    height = models.SmallIntegerField(null=True, blank=True)
    star_sign = models.CharField(max_length=32, null=True, blank=True)
    number_of_siblings = models.SmallIntegerField(null=True, blank=True)
    birthplace = models.CharField(max_length=32, null=True, blank=True)
    distinguishing_marks = models.CharField(max_length=32, null=True, blank=True)
    # stats
    weapon_skill = models.SmallIntegerField(validators=[MinValueValidator(0), MaxValueValidator(100)], default=20)
    ballistic_skill = models.SmallIntegerField(validators=[MinValueValidator(0), MaxValueValidator(100)], default=20)
    strength = models.SmallIntegerField(validators=[MinValueValidator(0), MaxValueValidator(100)], default=20)
    toughness = models.SmallIntegerField(validators=[MinValueValidator(0), MaxValueValidator(100)], default=20)
    agility = models.SmallIntegerField(validators=[MinValueValidator(0), MaxValueValidator(100)], default=20)
    intelligence = models.SmallIntegerField(validators=[MinValueValidator(0), MaxValueValidator(100)], default=20)
    will_power = models.SmallIntegerField(validators=[MinValueValidator(0), MaxValueValidator(100)], default=20)
    fellowship = models.SmallIntegerField(validators=[MinValueValidator(0), MaxValueValidator(100)], default=20)
    attacks = models.SmallIntegerField(validators=[MinValueValidator(0), MaxValueValidator(20)], default=1)
    wounds = models.SmallIntegerField(validators=[MinValueValidator(0), MaxValueValidator(100)], default=5)
    strength_bonus = models.SmallIntegerField(validators=[MinValueValidator(0), MaxValueValidator(20)], default=1)
    toughness_bonus = models.SmallIntegerField(validators=[MinValueValidator(0), MaxValueValidator(20)], default=1)
    movement = models.SmallIntegerField(validators=[MinValueValidator(0), MaxValueValidator(20)], default=1)
    magic = models.SmallIntegerField(validators=[MinValueValidator(0), MaxValueValidator(20)], default=0)
    insanity_points = models.SmallIntegerField(validators=[MinValueValidator(0), MaxValueValidator(10)], default=0)
    fate_points = models.SmallIntegerField(validators=[MinValueValidator(0), MaxValueValidator(10)], default=0)
    # functionalities
    user = models.ForeignKey(User, related_name='player', on_delete=models.CASCADE, blank=True, null=True)
    game_master = models.ForeignKey(User, related_name='game_master',  on_delete=models.CASCADE, blank=True, null=True)
    experience = models.SmallIntegerField(default=0)
    portrait = models.SmallIntegerField([MinValueValidator(1), MaxValueValidator(8)], blank=True, null=True)


class News(models.Model):
    title = models.CharField(max_length=32, default="News")
    content = models.TextField(null=True)
    date_added = models.DateTimeField(default=datetime.now, blank=True)
    added_by = models.ForeignKey(User, related_name='added_by', on_delete=models.CASCADE)
    category = models.CharField(max_length=32, blank=True, null=True)
    picture = models.ImageField(upload_to='news/%Y/%m/%d', default='news/default.jpg',
                                blank=True, null=True)

warhammer/forms.py
from django import forms
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.core.validators import MinValueValidator, MaxValueValidator, validate_email
from .models import Hero

# warhammer hero creation forms


def	validate_age(value):
    if value < 16 or value > 200:
        raise ValidationError("Wrong age")


def	validate_weight(value):
    if value < 30 or value > 150:
        raise ValidationError("Wrong weight")


def	validate_height(value):
    if value < 80 or value > 200:
        raise ValidationError("Wrong height")


def	validate_experience_assignment(value):
    if value < 1 or value > 2000:
        raise ValidationError("You have to assign a number between 1 and 2000")


def	validate_positive(value):
    if value < 0:
        raise ValidationError("Must be a positive number")


def validate_if_user_exists(user_name):
    if user_name != "":
        try:
            user = User.objects.get(username=user_name)
        except:
            raise ValidationError("There is no such user")


class HeroCreationCharacterForm(forms.Form):
    name = forms.CharField(label='Hero name', max_length=32)
    game_master_name = forms.CharField(label="Game master user name (leave empty if you don't want to assign one)",
                                       validators=[validate_if_user_exists],
                                       required=False)
    race = forms.ChoiceField(choices=(("human", "Human"),
                                      ("dwarf", "Dwarf"),
                                      ("elf", "Elf"),
                                      ("halfling", "Halfling"),))
    gender = forms.ChoiceField(choices=(("male", "Male"),
                                        ("female", "Female"),))
    current_career = forms.ChoiceField(choices=(
        ("agitator", "Agitator"), ("apprentice_wizard", "Apprentice Wizard"), ("bailiff", "Bailiff"),
        ("barber-surgeon", "Barber-Surgeon"), ("boatman", "Boatman"), ("bodyguard", "Bodyguard"),
        ("bone_picker", "Bone Picker"), ("bounty_hunter", "Bounty Hunter"), ("burgher", "Burgher"),
        ("camp_follower", "Camp Follower"), ("charcoal-burner", "Charcoal-Burner"),  ("coachman", "Coachman"),
        ("entertainer", "Entertainer"),  ("envoy", "Envoy"),  ("estalian_diestro", "Estalian Diestro"),
        ("ferryman", "Ferryman"), ("fieldwarden", "Fieldwarden"),  ("fisherman", "Fisherman"),
        ("grave_robber", "Grave Robber"),  ("hedge_wizard", "Hedge Wizard"),  ("hunter", "Hunter"),
        ("initiate", "Initiate"), ("jailer", "Jailer"),  ("kislevite_kossar", "Kislevite Kossar"),
        ("kithband_warrior", "Kithband Warrior"),  ("marine", "Marine"),  ("mercenary", "Mercenary"),
        ("messenger", "Messenger"),  ("militiaman", "Militiaman"),  ("miner", "Miner"),  ("noble", "Noble"),
        ("norse_berserker", "Norse Berserker"),  ("outlaw", "Outlaw"),  ("outrider", "Outrider"),
        ("peasant", "Peasant"),  ("pit_fighter", "Pit Fighter"),  ("protagonist", "Protagonist"),
        ("rat_catcher", "Rat Catcher"),  ("roadwarden", "Roadwarden"),  ("rogue", "Rogue"),
        ("runebearer", "Runebearer"),  ("scribe", "Scribe"),  ("seaman", "Seaman"),  ("servant", "Servant"),
        ("shieldbreaker", "Shieldbreaker"),  ("smuggler", "Smuggler"),  ("soldier", "Soldier"),
        ("squire", "Squire"),  ("student", "Student"),  ("thief", "Thief"),  ("thug", "Thug"),
        ("toll_keeper", "Toll Keeper"),  ("tomb_robber", "Tomb Robber"),  ("tradesman", "Tradesman"),
        ("troll_slayer", "Troll Slayer"),  ("vagabond", "Vagabond"),  ("valet", "Valet"),
        ("watchman", "Watchman"),  ("woodsman", "Woodsman"),  ("zealot", "Zealot"),
    ))


class HeroCreationPersonalDetailsForm(forms.Form):
    previous_careers = forms.CharField(label='Previous careers', max_length=32, required=False)
    age = forms.IntegerField(label="Age", validators=[validate_age], required=False)
    eye_color = forms.CharField(label='Eye color', max_length=16, required=False)
    hair_color = forms.CharField(label='Hair color', max_length=16, required=False)
    weight = forms.IntegerField(label='Weight', validators=[validate_weight], required=False)
    height = forms.IntegerField(label='Height', validators=[validate_height], required=False)
    star_sign = forms.CharField(label='Star sign', max_length=32, required=False)
    number_of_siblings = forms.IntegerField(label='Number of siblings', validators=[validate_positive], required=False)
    birthplace = forms.CharField(label='Birthplace', max_length=32, required=False)
    distinguishing_marks = forms.CharField(label="Distinguishing marks", max_length=32, required=False)


class HeroCreationCharacterProfileForm(forms.Form):
    weapon_skill = forms.IntegerField(validators=[MinValueValidator(0), MaxValueValidator(100)], widget=forms.TextInput(attrs={'readonly':'readonly'}))
    ballistic_skill = forms.IntegerField(validators=[MinValueValidator(0), MaxValueValidator(100)], widget=forms.TextInput(attrs={'readonly':'readonly'}))
    strength = forms.IntegerField(validators=[MinValueValidator(0), MaxValueValidator(100)], widget=forms.TextInput(attrs={'readonly':'readonly'}))
    toughness = forms.IntegerField(validators=[MinValueValidator(0), MaxValueValidator(100)], widget=forms.TextInput(attrs={'readonly':'readonly'}))
    agility = forms.IntegerField(validators=[MinValueValidator(0), MaxValueValidator(100)], widget=forms.TextInput(attrs={'readonly':'readonly'}))
    intelligence = forms.IntegerField(validators=[MinValueValidator(0), MaxValueValidator(100)], widget=forms.TextInput(attrs={'readonly':'readonly'}))
    will_power = forms.IntegerField(validators=[MinValueValidator(0), MaxValueValidator(100)], widget=forms.TextInput(attrs={'readonly':'readonly'}))
    fellowship = forms.IntegerField(validators=[MinValueValidator(0), MaxValueValidator(100)], widget=forms.TextInput(attrs={'readonly':'readonly'}))
    attacks = forms.IntegerField(validators=[MinValueValidator(0), MaxValueValidator(20)], widget=forms.TextInput(attrs={'readonly':'readonly'}))
    wounds = forms.IntegerField(validators=[MinValueValidator(0), MaxValueValidator(100)], widget=forms.TextInput(attrs={'readonly':'readonly'}))
    strength_bonus = forms.IntegerField(validators=[MinValueValidator(0), MaxValueValidator(20)], widget=forms.TextInput(attrs={'readonly':'readonly'}))
    toughness_bonus = forms.IntegerField(validators=[MinValueValidator(0), MaxValueValidator(20)], widget=forms.TextInput(attrs={'readonly':'readonly'}))
    movement = forms.IntegerField(validators=[MinValueValidator(0), MaxValueValidator(20)], widget=forms.TextInput(attrs={'readonly':'readonly'}))
    magic = forms.IntegerField(validators=[MinValueValidator(0), MaxValueValidator(20)], widget=forms.TextInput(attrs={'readonly':'readonly'}))
    insanity_points = forms.IntegerField(validators=[MinValueValidator(0), MaxValueValidator(10)], widget=forms.TextInput(attrs={'readonly':'readonly'}))
    fate_points = forms.IntegerField(validators=[MinValueValidator(0), MaxValueValidator(10)], widget=forms.TextInput(attrs={'readonly':'readonly'}))


class HeroSearchForm(forms.Form):
    name = forms.CharField(label='Hero name', max_length=32, required=False)
    race = forms.ChoiceField(choices=(("", "Any"),
                                      ("human", "Human"),
                                      ("dwarf", "Dwarf"),
                                      ("elf", "Elf"),
                                      ("halfling", "Halfling")), required=False)
    gender = forms.ChoiceField(choices=(("", "Any"),
                                        ("male", "Male"),
                                        ("female", "Female"),), required=False)
    current_career = forms.CharField(label='Current career', max_length=32, required=False)


class AssignExperienceForm(forms.Form):
    hero = forms.ModelChoiceField(queryset=Hero.objects.filter(game_master=1))
    experience = forms.IntegerField(label="How much experience would you like to assign?",
                                    validators=[validate_experience_assignment])

    def __init__(self, user, *args, **kwargs):
        super(AssignExperienceForm, self).__init__(*args, **kwargs)
        self.fields['hero'].queryset = Hero.objects.filter(game_master=user)


class GameMasterEditForm(forms.Form):
    game_master_name = forms.CharField(label='New game master user name',
                                       validators=[validate_if_user_exists])


# user management forms


class UserLoginForm(forms.Form):
    username = forms.CharField(label='User name')
    password = forms.CharField(label='Password', widget=forms.PasswordInput)


class AddUserForm(forms.Form):
    username = forms.CharField(label='User name')
    password = forms.CharField(label='Password', widget=forms.PasswordInput)
    repeat_password = forms.CharField(label='Repeat password', widget=forms.PasswordInput)
    first_name = forms.CharField(label='First name', required=False)
    last_name = forms.CharField(label='Last name', required=False)
    email = forms.CharField(label='E-mail', validators=[validate_email])


class AddNewsForm(forms.Form):
    title = forms.CharField(label='News title', max_length=32)
    content = forms.CharField(label='Content:', widget=forms.Textarea)
    picture = forms.ImageField(label='Picture', required=False)

templates/access_denied.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    Access denied
{% endblock %}
{% block content %}
    <h3>Access denied</h3>
    <p class="align-left">Sorry, you dont have access to this site. {{ message }}</p>
{% endblock %}

templates/add_news.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    Write news
{% endblock %}
{% block content %}
<h3>Create new article:</h3>
<form action="" method="post" enctype="multipart/form-data">
    <div class="input-block">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" class="button-centered" value="Add">
    </div>
</form>
{{ message }}
{% endblock %}

templates/edit_news.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    Write news
{% endblock %}
{% block content %}
<h3>Edit article:</h3>
<form action="" method="post" enctype="multipart/form-data">
    <div class="input-block">
        {% csrf_token %}
        <p>
            <label for="id_title">News title:</label>
            <input type="text" name="title" maxlength="32" required="" id="id_title" value="{{ news.title }}">
        </p>
        <p>
            <label for="id_content">Content:</label>
            <textarea name="content" cols="40" rows="10" required="" id="id_content">{{ news.content }}</textarea>
        </p>
        <p>
            <label for="id_picture">Picture:</label>
            <input type="file" name="picture" id="id_picture" value="{{ news.picture }}">
        </p>
        <input type="submit" class="button-centered" value="Add">
    </div>
</form>
{{ message }}
{% endblock %}

templates/user_profile.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    Create user
{% endblock %}
{% block content %}
<h3>{{ user.username.capitalize }} profile:</h3>
<div class="col-lg-5 col-md-5 col-sm-5 col-xs-8">
    <table class="no-border-table">
        <th colspan="2" class=category_header>{{ user.username }} </th>
        <tr><th><label for="id_first_name">First name:</label></th><td>{{ user.first_name }}</td></tr>
        <tr><th><label for="id_last_name">Last name:</label></th><td>{{ user.last_name }}</td></tr>
        <tr><th><label for="id_emial">Email:</label></th><td>{{ user.email }}</td></tr>
        <tr><th><label for="id_date_joined">Date Joined:</label></th><td>{{ user.date_joined }}</td></tr>
        <tr><th><label for="id_last_login">Last logged in:</label></th><td>{{ user.last_login }}</td></tr>
    </table>
</div>
<div class="col-lg-6 col-md-6 col-sm-6 col-xs-8 col-lg-offset-1 col-md-offset-1 col-sm-offset-2">
    <strong>User characters:</strong>
    <ul>
    {% for hero in user_heroes%}
        <div class="align-left">
            <li><a href='/warhammer/hero/{{ hero.id }}'><strong>{{ hero.name }}</strong></a> - {{ hero.race.capitalize }} {{ hero.current_career.capitalize }}
        </div>
        {% endfor %}
    </ul>
    <strong>Game master characters:</strong>
    <ul>
    {% for hero in game_master_heroes%}
        <div class="align-left">
            <li><a href='/warhammer/hero/{{ hero.id }}'><strong>{{ hero.name }}</strong></a> - {{ hero.race.capitalize }} {{ hero.current_career.capitalize }}
        </div>
        {% endfor %}
    </ul><br><br><br>
    <a href='/warhammer/assign-experience'><strong>Assign experience</strong></a>
</div>
{{ message }}
{% endblock %}

templates/warhammer_hero.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    {{ hero.name }}
{% endblock %}
{% block content %}
    <head>
    <title>RPG Hero creator -
    Warhammer hero creation
</title>

</head>
<body>
    <h3>{{ hero.name }}:</h3>
    <form action="" method="post">
    <div class="col-lg-3 col-md-3 col-sm-3 col-xs-8">
    <div class=character>
        <table class="hero-table">
            <th colspan="2" class=category_header>CHARACTER </th>
            <tr><th><label for="id_name">Hero name:</label></th><td>{{ hero.name }}</td></tr>
            <tr><th><label for="id_race">Race:</label></th><td>{{ hero.race.capitalize }}</td></tr>
            <tr><th><label for="id_gender">Gender:</label></th><td>{{ hero.gender.capitalize }}</td></tr>
            <tr><th><label for="id_current_career">Current career:</label></th><td>{{ hero.current_career.capitalize }}</td></tr>
            <form action="" method="post">
                {% csrf_token %}
                <tr><th><label for="id_player">Player:</label></th><td><a href='/user-profile/{{ hero.user.id }}'>{{ hero.user.username }}</a></td></tr>
                <tr><th><label for="id_game_master">Game master:</label></th><td><a href='/user-profile/{{ hero.game_master.id }}'>{{ hero.game_master.username }}</a></td></tr>
                <tr><th><label for="id_experience">Experience:</label></th><td>{{ hero.experience }}</td></tr>
            </form>
        </table>
    </div>
    <br>
    <div class="character-personal-details">
        <table class="hero-table">
            <th colspan="2" class=category_header>PERSONAL DETAILS
            <tr><th><label for="id_previous_careers">Previous careers:</label></th><td>{{ hero.previous_careers}}</td></tr>
            <tr><th><label for="id_age">Age:</label></th><td>{% if hero.age == None %} {% else %}{{ hero.age }}{% endif %}</td></tr>
            <tr><th><label for="id_eye_color">Eye color:</label></th><td>{{ hero.eye_color }}</td></tr>
            <tr><th><label for="id_hair_color">Hair color:</label></th><td>{{ hero.hair_color }}</td></tr>
            <tr><th><label for="id_weight">Weight:</label></th><td>{% if hero.age == None %} {% else %}{{ hero.weight }}{% endif %}</td></tr>
            <tr><th><label for="id_height">Height:</label></th><td>{% if hero.age == None %} {% else %}{{ hero.height }}{% endif %}</td></tr>
            <tr><th><label for="id_star_sign">Star sign:</label></th><td>{{ hero.star_sign }}</td></tr>
            <tr><th><label for="id_number_of_siblings">Number of siblings:</label></th><td>{% if hero.age == None %} {% else %}{{ hero.number_of_siblings }}{% endif %}</td></tr>
            <tr><th><label for="id_birthplace">Birthplace:</label></th><td>{{ hero.birthplace }}</td></tr>
            <tr><th><label for="id_distinguishing_marks">Distinguishing marks:</label></th><td>{{ hero.distinguishing_marks }}</td></tr>
        </table>
    </div>
    <br>
    <div class="character-profile-table">
        <table class="hero-table">
            <th colspan="9" class=category_header>CHARACTER PROFILE</th>
            <tr>
                <td>Main</td><td>WS</td><td>BS</td><td>S</td><td>T</td><td>Ag</td><td>Int</td><td>WP</td><td>Fel</td>
            </tr>
            <tr>
                <td class="no-border">Starting</td>
                <td>{{ hero.weapon_skill }}</td>
                <td>{{ hero.ballistic_skill }}</td>
                <td>{{ hero.strength }}</td>
                <td>{{ hero.toughness }}</td>
                <td>{{ hero.agility }}</td>
                <td>{{ hero.intelligence }}</td>
                <td>{{ hero.will_power }}</td>
                <td>{{ hero.fellowship }}</td>
            </tr>
            <tr>
                <td class="no-border">Advance</td><td><input type="number" disabled></td>
                <td><input type="number" disabled></td><td><input type="number" disabled></td>
                <td><input type="number" disabled></td><td><input type="number" disabled></td>
                <td><input type="number" disabled></td><td><input type="number" disabled></td>
                <td><input type="number" disabled></td>
            </tr>
            <tr>
                <td class="no-border">Current</td><td><input type="number" disabled></td>
                <td><input type="number" disabled></td><td><input type="number" disabled></td>
                <td><input type="number" disabled></td><td><input type="number" disabled></td>
                <td><input type="number" disabled></td><td><input type="number" disabled></td>
                <td><input type="number" disabled></td>
            </tr>
            <tr>
                <td>Secondary</td><td>A</td><td>W</td><td>SB</td><td>TB</td><td>M</td><td>Mag</td><td>IP</td><td>FP</td>
            </tr>
            <tr>
                <td class="no-border">Starting</td>
                <td>{{ hero.attacks }}</td>
                <td>{{ hero.wounds }}</td>
                <td>{{ hero.strength_bonus }}</td>
                <td>{{ hero.toughness_bonus }}</td>
                <td>{{ hero.movement }}</td>
                <td>{{ hero.magic }}</td>
                <td>{{ hero.insanity_points }}</td>
                <td>{{ hero.fate_points }}</td>
            </tr>
            </tr>
            <tr>
                <td class="no-border">Advance</td><td><input type="number" disabled></td>
                <td><input type="number" disabled></td><td><input type="number" disabled></td>
                <td><input type="number" disabled></td><td><input type="number" disabled></td>
                <td><input type="number" disabled></td><td><input type="number" disabled></td>
                <td><input type="number" disabled></td>
            </tr>
            <tr>
                <td class="no-border">Current</td><td><input type="number" disabled></td>
                <td><input type="number" disabled></td><td><input type="number" disabled></td>
                <td><input type="number" disabled></td><td><input type="number" disabled></td>
                <td><input type="number" disabled></td><td><input type="number" disabled></td>
                <td><input type="number" disabled></td>
            </tr>
        </table>
        <br>
    </div>
    </div>
        <div class="character-picture col-lg-3 col-md-3 col-sm-3 col-xs-8 col-lg-offset-4 col-md-offset-4 col-sm-offset-5">
            <div class="right-side">
                <img src="/static/portraits/warhammer/{{ hero.race }}/{{ hero.gender }}/{{ hero.portrait }}.jpg" alt="Hero Portrait" id="id_portrait" name="id_portrait">
            </div>
        </div>

    </form>
    <link rel="stylesheet" type="text/css" href="/static/css/warhammer.css" />
{% endblock %}